// phases/03-github.js — Create GitHub repo, commit, push, create dev branch

import { logger } from '../lib/logger.js'
import { exec } from '../lib/exec.js'
import { github } from '../lib/api.js'

export async function runGithub(cfg, inputs, appDir) {
  logger.phase('2', 'GitHub')

  const { appName } = inputs
  const username    = cfg.github.username
  const repoName    = appName
  const repoFull    = `${username}/${repoName}`

  // 2a. Create repo (skip if already exists)
  logger.step(`Creating private GitHub repo: ${repoFull}`)
  const exists = await github.repoExists(cfg, repoName)

  let repoUrl
  if (exists) {
    logger.warn(`Repo ${repoFull} already exists — using it`)
    repoUrl = `https://github.com/${repoFull}.git`
  } else {
    const repo = await github.createRepo(cfg, repoName)
    repoUrl    = repo.clone_url
    logger.success(`Repo created: ${repo.html_url}`)
  }

  // 2b. Set git remote using token-authenticated URL
  // Token is embedded in the URL for one-time push — not stored in git config
  const authedUrl = `https://x-access-token:${cfg.github.token}@github.com/${repoFull}.git`

  // Remove existing remote if present, then re-add
  await exec('git remote remove origin', { cwd: appDir, silent: true }).catch(() => {})
  await exec(`git remote add origin ${authedUrl}`, { cwd: appDir })

  // 2c. Stage and commit everything
  logger.step('Staging and committing initial files')
  await exec('git add -A', { cwd: appDir })

  const authorName  = `${username}`
  const authorEmail = cfg.github.email

  const { stdout: statusOut } = await exec('git status --porcelain', { cwd: appDir })
  if (statusOut) {
    await exec(
      `git -c user.name="${authorName}" -c user.email="${authorEmail}" ` +
      `commit -m "chore: bootstrap ${appName}" -m "Generated by household-app-infrastructure"`,
      { cwd: appDir }
    )
    logger.success('Initial commit created')
  } else {
    logger.warn('Nothing to commit — skipping initial commit')
  }

  // 2d. Push main branch
  logger.step('Pushing to GitHub (main)')
  await exec('git push -u origin main', { cwd: appDir })
  logger.success('main branch pushed')

  // 2e. Create and push dev branch
  logger.step('Creating dev branch')
  const { stdout: devBranchOut } = await exec('git branch --list dev', { cwd: appDir })
  if (devBranchOut) {
    logger.warn('dev branch already exists — skipping creation')
  } else {
    await exec('git checkout -b dev', { cwd: appDir })
    await exec('git push -u origin dev', { cwd: appDir })
  }
  await exec('git checkout main', { cwd: appDir })
  logger.success('dev branch created and pushed')

  // 2f. Remove token from remote URL (replace with plain HTTPS)
  // Keeps the token out of git config after bootstrap
  await exec(`git remote set-url origin https://github.com/${repoFull}.git`, { cwd: appDir })

  logger.success(`Phase 2 complete — https://github.com/${repoFull}`)
  return { repoFull, repoUrl: `https://github.com/${repoFull}` }
}
